# action.yml
name: "Hook"
description: "Run hook plugins"
inputs:
  hmac: # id of input
    description: "HMAC secret"
    required: true
  gh-app-id-pivate-key: # id of input
    description: "HMAC secret"
    required: true
  plugin-to-run: # id of input
    description: "Name a plugin to launch"
    required: true
    default: "size"
outputs:
  time: # id of output
    description: "The time plugin ran"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.plugin-to-run }}
